### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/solidity#1]
See https://github.com/exercism/problem-specifications/tree/master/workflows#migrating-from-travis

**Comment by ali2251** [comment]
This is done now, need to fix some tests but using Github actions now, Let me know if i missed anything!

**Comment by ErikSchierboom** [comment]
@ali2251 Looks good! The only thing remaining is to remove the `.travis.yml` file.

**Comment by ali2251** [comment]
Done!
