### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/solidity#55]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/solidity/runs/3066727504

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by kotp** [comment]
Not enough rights here to update the link in the issue description.  So I am providing a non-expired run here:

https://github.com/exercism/solidity/runs/3986279324
